# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sew < Formula
  desc "Kubernetes application stacks for dev, test, and CI"
  homepage "https://a-cordier.github.io/sew/"
  version "0.18.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/a-cordier/sew/releases/download/v0.18.1/sew_0.18.1_darwin_amd64.zip"
      sha256 "5ab972569bb3b708c78d6bece2152c9b9183b882905528e6de1557156fdc66a4"

      define_method(:install) do
        bin.install "sew"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/a-cordier/sew/releases/download/v0.18.1/sew_0.18.1_darwin_arm64.zip"
      sha256 "ffdfe8564f4c0feb1958dcea8a124909841715c5b53c1b34d7c96a654ca2346e"

      define_method(:install) do
        bin.install "sew"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/a-cordier/sew/releases/download/v0.18.1/sew_0.18.1_linux_amd64.tar.gz"
      sha256 "9d6d22347b2ad1dfc85dff1d161f73b74705f1c33888c6f0fe24a9dbc8856115"
      define_method(:install) do
        bin.install "sew"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/a-cordier/sew/releases/download/v0.18.1/sew_0.18.1_linux_arm64.tar.gz"
      sha256 "2dee47e8d5ffaf8c378ee2554dcbdbaa0354522bd320b6b3756de97fdd1815f1"
      define_method(:install) do
        bin.install "sew"
      end
    end
  end

  test do
    system "#{bin}/sew", "version"
  end
end
