# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sew < Formula
  desc "Kubernetes application stacks for dev, test, and CI"
  homepage "https://a-cordier.github.io/sew/"
  version "0.11.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/a-cordier/sew/releases/download/v0.11.0/sew_0.11.0_darwin_amd64.zip"
      sha256 "5becc6a8ba9efaba621383868f53fb610055876864c8abef96bacffab5c9be94"

      define_method(:install) do
        bin.install "sew"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/a-cordier/sew/releases/download/v0.11.0/sew_0.11.0_darwin_arm64.zip"
      sha256 "853af0dc7b19a0e4eaa2d14f424a13ff04e3869a43c3ea5b0991c1a113497980"

      define_method(:install) do
        bin.install "sew"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/a-cordier/sew/releases/download/v0.11.0/sew_0.11.0_linux_amd64.tar.gz"
      sha256 "c2286d88588e5c326fcbae728f019db7acf70934de07b3af8c9b2cc851ef535d"
      define_method(:install) do
        bin.install "sew"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/a-cordier/sew/releases/download/v0.11.0/sew_0.11.0_linux_arm64.tar.gz"
      sha256 "62b9ea7b379714bf052d2185c6b0a1044ebe8d72df0090a6e062bb4c91d67477"
      define_method(:install) do
        bin.install "sew"
      end
    end
  end

  test do
    system "#{bin}/sew", "version"
  end
end
