version: 2

builds:
  - main: .
    binary: sew
    ldflags:
      - -s -w -X main.version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format_overrides:
      - goos: darwin
        formats:
          - zip

changelog:
  disable: true
