api:
  enabled: false

portal:
  enabled: false

ui:
  enabled: false

es:
  enabled: false

ratelimit:
  type: 
    none

gateway:
  replicaCount: 1
  autoscaling:
    enabled: false
  image:
    repository: graviteeio/apim-gateway
    tag: latest
  ingress:
    enabled: false
  services:
    sync:
      kubernetes:
        enabled: true
  dbLess: true
  reporters:
    elasticsearch:
      enabled: false
