image: docker.elastic.co/elasticsearch/elasticsearch
imageTag: 9.3.1

clusterName: elasticsearch
nodeGroup: master

replicas: 1
minimumMasterNodes: 1
esJavaOpts: "-Xmx256m -Xms256m"

createCert: false

extraEnvs:
  - name: xpack.security.enabled
    value: "false"

protocol: http

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

persistence:
  enabled: false
